#!/usr/bin/env python3
"""Row inventory for the fluidity pass. Re-run after every pack; paste the output into ROW-INVENTORY.md.

Per fighter: cell count per row, rows whose cells REPEAT (a hold baked as a duplicate cell),
rows that ALIAS another row cell-for-cell (two names, one drawing), and which transition
keys exist. A repeat or an alias is where a frame-by-frame pass has nothing to play yet.
"""
import json, re, collections, sys, pathlib
SP = pathlib.Path(__file__).resolve().parents[3] / 'web' / 'assets' / 'sprites'
NAMES = ['mizu', 'shin', 'tsubasa', 'ember', 'kael', 'executioner', 'mokurai', 'exile']
NEED = ['walk1', 'njump1', 'turn1', 'jsquat1', 'land1', 'skid1', 'xidle1', 'run_clean1', 'airhurt1']
out = []
for n in NAMES:
    p = SP / f'{n}.json'
    if not p.exists(): out.append(f'## {n}\nMISSING {p}\n'); continue
    d = json.load(open(p)); F = d['frames']
    rows = collections.defaultdict(list)
    for k, v in F.items():
        m = re.match(r'^([a-z_]+?)(\d+)$', k)
        if m: rows[m.group(1)].append((int(m.group(2)), v))
    by = lambda r: [v for _, v in sorted(rows[r])]
    dup = [f'`{r}` {len(rows[r])}c/{len(set(by(r)))}u' for r in sorted(rows) if len(rows[r]) >= 3 and len(set(by(r))) < len(rows[r])]
    alias = [f'`{a}`=`{b}`' for a in sorted(rows) for b in sorted(rows) if a < b and len(rows[a]) >= 3 and set(by(a)) == set(by(b))]
    missing = [k for k in NEED if k not in F]
    counts = ', '.join(f'{r} {len(c)}' for r, c in sorted(rows.items()))
    orphans = sum(1 for i in range(d['cols']) if i not in set(F.values()))  # packed cells no key points at: LOOK here before drawing new
    out.append(f'## {n} — {d["cols"]} cells, {len(rows)} rows, frame {d["frameW"]}x{d["frameH"]} footY {d["footY"]}\n'
               f'- missing keys: {", ".join(f"`{k}`" for k in missing) or "none"}\n'
               f'- repeated cells: {", ".join(dup) or "none"}\n'
               f'- aliased rows: {", ".join(alias) or "none"}\n'
               f'- orphan cells (no key): {orphans}\n'
               f'- counts: {counts}\n')
print('# Row inventory (generated by inventory.py — do not hand-edit)\n')
print('\n'.join(out))
